name: Test Action

on:
  push:
    branches: [main]
  issues:
    types: [opened, edited]

jobs:
  check-marker:
    name: Check Marker
    runs-on: ubuntu-latest
    steps:
      - name: check
        id: check
        run: |
          echo "continue=${{ github.event.issue == null && true || startsWith(github.event.issue.body, '<!-- ISSUE TRACKER ENABLE -->') }}" >> $GITHUB_OUTPUT
    outputs:
      continue: ${{ steps.check.outputs.continue }}
  run-tracker:
    needs: check-marker
    if: ${{ needs.check-marker.outputs.continue }}
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      issues: write
    name: Run Tracker
    runs-on: [ubuntu-latest]
    steps:
      - name: setup aya
        id: setup-aya
        uses: 'HoshinoTented/setup-aya@v1'
        with:
          refs: 'main'
      - name: checkout
        uses: 'actions/checkout@v4'
      - name: run tracker
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ github.event.issue.number }}
