name: Test Action

on:
  push:
    branches: [main]
  issues:
    types: [opened, edited]

jobs:
  run-tracker:
    defaults:
      run:
        shell: bash
    permissions:
      contents: read
      issues: write
    name: Run Tracker
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout setup-aya
        uses: 'actions/checkout@v4'
        with:
          repository: HoshinoTented/actions
          refs: main
          token: ${{ secrets.PAT }}
      - name: setup aya
        id: setup-aya
        uses: 'HoshinoTented/actions@main'
        with:
          refs: 'issue-checker'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout
        uses: 'actions/checkout@v4'
      - run: ls /opt/hostedtoolcache/aya
      - name: run tracker
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ github.event.issue.number }}
