name: Test Action

on:
  push:
    branches: [main]
  issues:
    types: [opened, edited]

jobs:
  run-tracker:
    permissions:
      contents: read
      issues: write
    name: Run Tracker
    runs-on: [ubuntu-latest]
    steps:
      - name: setup java
        uses: 'actions/setup-java@v4'
        with:
          distribution: 'liberica'
          java-version: 21
      - name: setup aya
        uses: 'HoshinoTented/actions@main'
        with:
          version: 'nightly-build'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: checkout
        uses: 'actions/checkout@v4'
      - name: run tracker
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue: ${{ github.event.issue.number }}
